---
title: "CodeBook"
author: "Kelsey Herod"
date: "2025-11-24"
output: pdf_document
---

Data Overview:

DATASET: Human Activity Recognition Using Smartphones
Source: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones
Download: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

The Human Activity Recognition (HAR) dataset was built from recordings of 30 subjects performing daily living activities 
wearing a smartphone (Samsung Galaxy S II) on the waist with inertial sensors. The dataset consists of 10,299 instances collected 
using the accelerometer and gyroscope of the smartphone. Each subject within an age bracket of 19-48 years performed six activities: 
WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, and LAYING. Sensor signals were captured at 50Hz and video-recorded to 
manually label the activities. The data was then split into a training set containing 70% of subjects and a test set containing 30% of subjects.


Variable Descriptions:

Subjects — Volunteer ID (1–30)
Activities — Performed activities ((WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)

Features (Class: Numeric, Units: Hz, Seconds,  XYZ attached to each variable represents the 3-axial raw signals)

TimeBodyAccelerationMeanXYZ
TimeBodyAccelerationSTDXYZ
TimeGravityAccelerationMeanXYZ
TimeGravityAccelerationSTDXYZ
TimeBodyAccelerationJerkMeanXYZ
TimeBodyAccelerationJerkSTDXYZ
TimeBodyGyroscopeMeanXYZ
TimeBodyGyroscopeSTDXYZ
TimeBodyGyroscopeJerkMeanXYZ
TimeBodyGyroscopeJerkSTDXYZ
TimeBodyAccelerationMagnitudeMean
TimeBodyAccelerationMagnitudeSTD
TimeGravityAccelerationMagnitudeMean
TimeGravityAccelerationMagnitudeSTD
TimeBodyAccelerationJerkMagnitudeMean
TimeBodyAccelerationJerkMagnitudeSTD
TimeBodyGyroscopeMagnitudeMean
TimeBodyGyroscopeMagnitudeSTD
TimeBodyGyroscopeJerkMagnitudeMean
TimeBodyGyroscopeJerkMagnitudeSTD
FrequencyBodyAccelerationMeanXYZ
FrequencyBodyAccelerationSTDXYZ
FrequencyBodyAccelerationJerkMeanXYZ
FrequencyBodyAccelerationJerkSTDXYZ
FrequencyBodyGyroscopeMeanXYZ
FrequencyBodyGyroscopeSTDXYZ
FrequencyBodyAccelerationMagnitudeMean
FrequencyBodyAccelerationMagnitudeSTD
FrequencyBodyAccelerationJerkMagnitudeMean
FrequencyBodyAccelerationJerkMagnitudeSTD
FrequencyBodyGyroscopeMagnitudeMean
FrequencyBodyGyroscopeMagnitudeSTD
FrequencyBodyGyroscopeJerkMagnitudeMean
FrequencyBodyGyroscopeJerkMagnitudeSTD


Missing Data Handling: Explanation of how missing values were handled in the dataset.

Applying the command sum(is.na(merged_data)) prior to cleaning the merged dataset revealed that there are no missing values.


Data Processing:

Code list used to clean, transform and manipulate the data
rbind() - Combine rows
colnames() - Assign column names
cbind() - Combine datasets
str_which() - Find columns containing mean() and std()
merge() - Merge datasets by shared reference column
setdiff() - Restructure column order
names() - Change column names
gsub() - Search and replace current text with desired text
groupby() - Organize data into groups
summarize() - Creates summary column of summary statistics

Code Instructions:

Start at the top of the script and run code in chunks by section. Utilize the "How to verify results" code in README.md to double-check code application accuracy.


Analysis Description: Details of the analyses performed or planned.

The purpose of using this data is to demonstrate our groups ability to collect, work with, and clean a dataset. The goal is to prepare 
tidy data that can be used for further analysis. 




